#ifndef RT_CONFIG_H__
#define RT_CONFIG_H__

/* Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib) */

/* RT-Thread Kernel */

#define RT_NAME_MAX 8
#define RT_ALIGN_SIZE 4
#define RT_THREAD_PRIORITY_32
#define RT_THREAD_PRIORITY_MAX 32
#define RT_TICK_PER_SECOND 1000
#define RT_USING_OVERFLOW_CHECK
#define RT_USING_HOOK
#define RT_USING_IDLE_HOOK
#define RT_IDEL_HOOK_LIST_SIZE 4
#define IDLE_THREAD_STACK_SIZE 256
#define RT_USING_TIMER_SOFT
#define RT_TIMER_THREAD_PRIO 4
#define RT_TIMER_THREAD_STACK_SIZE 512
#define RT_DEBUG
#define RT_DEBUG_COLOR
#define RT_DEBUG_INIT_CONFIG
#define RT_DEBUG_INIT 1
#define RT_DEBUG_THREAD_CONFIG
#define RT_DEBUG_THREAD 1
#define RT_DEBUG_SCHEDULER_CONFIG
#define RT_DEBUG_SCHEDULER 1
#define RT_DEBUG_IPC_CONFIG
#define RT_DEBUG_IPC 1
#define RT_DEBUG_TIMER_CONFIG
#define RT_DEBUG_TIMER 1
#define RT_DEBUG_IRQ_CONFIG
#define RT_DEBUG_IRQ 1
#define RT_DEBUG_MEM_CONFIG
#define RT_DEBUG_MEM 1
#define RT_DEBUG_SLAB_CONFIG
#define RT_DEBUG_SLAB 1
#define RT_DEBUG_MEMHEAP_CONFIG
#define RT_DEBUG_MEMHEAP 1
#define RT_DEBUG_MODULE_CONFIG
#define RT_DEBUG_MODULE 1

/* Inter-Thread communication */

#define RT_USING_SEMAPHORE
#define RT_USING_MUTEX
#define RT_USING_EVENT
#define RT_USING_MAILBOX
#define RT_USING_MESSAGEQUEUE
#define RT_USING_SIGNALS
/* end of Inter-Thread communication */

/* Memory Management */

#define RT_USING_MEMPOOL
#define RT_USING_MEMHEAP
#define RT_USING_MEMHEAP_AS_HEAP
#define RT_USING_HEAP
/* end of Memory Management */
#define RT_USING_CONSOLE
#define RT_CONSOLEBUF_SIZE 256
#define RT_VER_NUM 0x30104
/* end of RT-Thread Kernel */
#define ARCH_ARM
#define ARCH_ARM_CORTEX_M
#define ARCH_ARM_CORTEX_M4

/* RT-Thread Components */

#define RT_USING_COMPONENTS_INIT
#define RT_USING_USER_MAIN
#define RT_MAIN_THREAD_STACK_SIZE 2048
#define RT_MAIN_THREAD_PRIORITY 10

/* Command shell */

/* end of Command shell */
/* end of RT-Thread Components */
#define RT_STUDIO_BUILT_IN

#endif
